---
- name: Configure hostname and interface on Junos router over SSH
  hosts: junos
  gather_facts: no
  vars:
    ansible_network_os: junos
    ansible_connection: netconf
    ansible_user: "{{ router_user | default('admin') }}"
    ansible_password: "{{ router_pass | default('admin@123') }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Configure hostname
      junipernetworks.junos.junos_config:
        lines:
          - "set system host-name {{ hostname }}"

    - name: Configure interface ge-0/0/0
      junipernetworks.junos.junos_config:
        lines:
          - "set interfaces ge-0/0/0 unit 0 family inet address {{ interface_ip }}/24"
          - "set interfaces ge-0/0/0 description '{{ interface_description }}'"
        comment: "Configured by Ansible"
        update: merge
        confirm_commit: true

    - name: Commit configuration
      debug: 
        msg: "Configuration committed successfully"
      
