- name: Quick test
  hosts: all 
  gather_facts: no
  connection: ansible.netcommon.netconf
  vars:
    ansible_network_os: junos
    ansible_port: 830

  tasks:
    - name: Get software information
      junipernetworks.junos.junos_rpc:
        rpc: get-software-information
      register: output

    - name: Print output
      debug:
        var: output
