- name: Shell test
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show EE collection list
      command: "ansible-galaxy collection list"
      register: result

    - name: Display collection list
      debug:
        var: result.stdout_lines

    - name: Show collection path
      debug:
        var: lookup('env', 'ANSIBLE_COLLECTIONS_PATH')


