---
- name: Render configuration from template using extra_vars
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Render the configuration file from Jinja2 template
      template:
        src: ./templates/cisco.j2
        dest: rendered_config.txt
      vars:
        hostname: "{{ hostname}}"
        interface_name: "{{ interface_name }}"
        interface_ip: "{{ interface_ip }}"
        subnet_mask: "{{ subnet_mask }}"
        description: "{{ description }}"

    - name: Show the rendered config in stdout
      ansible.builtin.shell: cat rendered_config.txt
      register: config_output

    - name: Print formatted config
      debug:
        msg: "{{ config_output.stdout_lines }}"

